# Generated by Django 3.2.7 on 2021-10-04 19:46

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0003_product_image'),
    ]

    operations = [
        migrations.RenameField(
            model_name='order',
            old_name='taxtPrice',
            new_name='taxPrice',
        ),
    ]
