# Generated by Django 3.2.7 on 2021-10-13 08:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0005_alter_product_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='image',
            field=models.ImageField(blank=True, default='/FM-801-min.jpeg', null=True, upload_to=''),
        ),
    ]
